version: '2'
services:
    dhanu-app:
        image: dhanu
        external_links:
            - dhanu-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dhanu?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dhanu-mysql:
        extends:
            file: mysql.yml
            service: dhanu-mysql
